# Actuator configuration type definition
!cfg.include config/fcf/devmgr/definitions/device.yaml:

# Actuator configuration for the controller
!cfg.typedef ActuatorController:
    low_on       : !cfg.type:boolean false   # If T, signal is active low
    low_switch   : !cfg.type:boolean false   # If T, signal is active low
    initial_state : !cfg.type:boolean false   # if T, actuator will be initially off
    maxon        : !cfg.type:uint32 2000
    timeout      : !cfg.type:uint32 2000

!cfg.typedef Actuator(DeviceOpcua):
    type:    !cfg.type:string Actuator
    mapfile: !cfg.type:string "config/fcf/devmgr/mapping/actuator.yaml"
    ctrl_config: !cfg.type:ActuatorController
