!cfg.include config/fcs/definitions/mosMap.yaml:

Mos: !cfg.type:MosMap
  cfg:
    timeout:       cfg.nTimeout
  stat:
    state:         stat.nState
    substate:      stat.nSubstate
    status:        stat.nStatus
    local:         stat.bLocal
    error_code:    stat.nErrorCode
  rpc:
    rpcInit:       RPC_Init
    rpcEnable:     RPC_Enable
    rpcDisable:    RPC_Disable
    rpcStop:       RPC_Stop
    rpcReset:      RPC_Reset
    rpcPing:       RPC_Ping



