
InfoDate:              info.sDate
InfoDescription:       info.sDescription
InfoName:              info.sName
InfoPlatform:          info.sPlatform
InfoSynopsis:          info.sSynopsis
InfoVersionMajor:      info.nVersionMajor
InfoVersionMinor:      info.nVersionMinor

CtrlExecute:           ctrl.bExecute
CtrlIntensity:         ctrl.lrIntensity(Double)
CtrlCommand:           ctrl.nCommand
CtrlPosUser1:          ctrl.lrPosUser[0].lrValue(Double)
CtrlPosUser2:          ctrl.lrPosUser[1].lrValue(Double)
CtrlPosUser3:          ctrl.lrPosUser[2].lrValue(Double)
CtrlPosBit1:           ctrl.nPosBit[0].nValue(Int16)
CtrlPosBit2:           ctrl.nPosBit[1].nValue(Int16)
CtrlPosBit3:           ctrl.nPosBit[2].nValue(Int16)

CfgDebug:              cfg.bDebug
CfgLogExtTime:         cfg.bLogExtTime
CfgLog:                cfg.bLog
CfgName:               cfg.sName
CfgTimeout:            cfg.nTimeout(UInt32)
CfgMaxOn:              cfg.nMaxOn
CfgNumAxes:            cfg.nNumAxes(Int16)
CfgFullRange1:         cfg.nFullRange[0].nValue(Int16)
CfgFullRange2:         cfg.nFullRange[1].nValue(Int16)
CfgFullRange3:         cfg.nFullRange[2].nValue(Int16)
CfgHome1:              cfg.nHome[0].nValue(Int16)
CfgHome2:              cfg.nHome[1].nValue(Int16)
CfgHome3:              cfg.nHome[2].nValue(Int16)
CfgLimitLow1:          cfg.nLimitLow[0].nValue(Int16)
CfgLimitLow2:          cfg.nLimitLow[1].nValue(Int16)
CfgLimitLow3:          cfg.nLimitLow[2].nValue(Int16)
CfgLimitHigh1:         cfg.nLimitHigh[0].nValue(Int16)
CfgLimitHigh2:         cfg.nLimitHigh[1].nValue(Int16)
CfgLimitHigh3:         cfg.nLimitHigh[2].nValue(Int16)
CfgUser2BitInput1:     cfg.lrUser2Bit_Get[0].lrValue(Double)
CfgUser2BitInput2:     cfg.lrUser2Bit_Get[1].lrValue(Double)
CfgUser2BitInput3:     cfg.lrUser2Bit_Get[2].lrValue(Double)
CfgUser2OffsetInput1:  cfg.nUserOffsetBit_Get[0].nValue(Int16)
CfgUser2OffsetInput2:  cfg.nUserOffsetBit_Get[1].nValue(Int16)
CfgUser2OffsetInput3:  cfg.nUserOffsetBit_Get[2].nValue(Int16)
CfgUser2BitOutput1:    cfg.lrUser2Bit_Set[0].lrValue(Double)
CfgUser2BitOutput2:    cfg.lrUser2Bit_Set[1].lrValue(Double)
CfgUser2BitOutput3:    cfg.lrUser2Bit_Set[2].lrValue(Double)
CfgUser2OffsetOutput1: cfg.nUserOffsetBit_Set[0].nValue(Int16)
CfgUser2OffsetOutput2: cfg.nUserOffsetBit_Set[1].nValue(Int16)
CfgUser2OffsetOutput3: cfg.nUserOffsetBit_Set[2].nValue(Int16)

StatActionDesc:        stat.sActionDesc
StatCycleCounter:      stat.nCycleCounter(UInt32)
StatErrorCode:         stat.nErrorCode
StatErrorText:         stat.sErrorText
StatEventDesc:         stat.sEventDesc
StatHwStatus:          stat.sHwStatus
StatHwStatusNum:       stat.nHwStatus
StatLastCommand:       stat.sLastCommand
StatLastCommandNum:    stat.nLastCommand
StatLibVersion:        stat.sLibVersion
StatLocal:             stat.bLocal
StatRpcErrorCode:      stat.nRpcErrorCode
StatRpcErrorText:      stat.sRpcErrorText
StatState:             stat.sState
StatStateNum:          stat.nState
StatStatus:            stat.sStatus
StatStatusNum:         stat.nStatus
StatSubstate:          stat.sSubstate
StatSubstateNum:       stat.nSubstate
StatActPosBit1:        stat.nActPosBit[0].nValue(Int32)
StatActPosBit2:        stat.nActPosBit[1].nValue(Int32)
StatActPosBit3:        stat.nActPosBit[2].nValue(Int32)
StatActPosUser1:       stat.lrActPosUsr[0].lrValue(Double)
StatActPosUser2:       stat.lrActPosUsr[1].lrValue(Double)
StatActPosUser3:       stat.lrActPosUsr[2].lrValue(Double)

StatMonActPosBit1:     stat.monActPosBit_0(Int32)
StatMonActPosBit2:     stat.monActPosBit_1(Int32)
StatMonActPosBit3:     stat.monActPosBit_2(Int32)
StatMonActPosUser1:    stat.monActPosUsr_0(Double)
StatMonActPosUser2:    stat.monActPosUsr_1(Double)
StatMonActPosUser3:    stat.monActPosUsr_2(Double)
StatMonSetPosBit1:     stat.monSetPosBit_0(Int32)
StatMonSetPosBit2:     stat.monSetPosBit_1(Int32)
StatMonSetPosBit3:     stat.monSetPosBit_2(Int32)

RpcDisable:            rpc.Disable(O:ReturnValue(Int16))
RpcEnable:             rpc.Enable(O:ReturnValue(Int16))
RpcExit:               rpc.Exit(O:ReturnValue(Int16))
RpcInit:               rpc.Init(O:ReturnValue(Int16))
RpcReset:              rpc.Reset(O:ReturnValue(Int16))
RpcState:              rpc.State(O:StateStat(String))
RpcStop:               rpc.Stop(O:ReturnValue(Int16))
RpcAuto:               rpc.Auto(O:ReturnValue(Int16))
RpcPos:                rpc.Pos(O:ReturnValue(Int16))
RpcHome:               rpc.Home(O:ReturnValue(Int16))
RpcMoveBit:            rpc.MoveBit(I:in_nPos1(Int16), I:in_nPos2(Int16), I:in_nPos3(Int16), O:ReturnValue(Int16))
RpcMoveUser:           rpc.MoveUser(I:in_lrPos1(Double), I:in_lrPos2(Double), I:in_lrPos3(Double), O:ReturnValue(Int16))
