!cfg.include config/fcf/devmgr/definitions/shutter.yaml:

# Please note some parameters are inherited and therefore not defined here.
shutter1: !cfg.type:Shutter
  overview: 'Shutter device example 1'
  description: "Shutter device example 1 description"
  identifier: PLC1
  prefix: MAIN.Shutter2
  dev_endpoint: opc.tcp://134.171.59.99:4840
  sim_endpoint: opc.tcp://134.171.2.213:7576
  fits_prefix: "SHUT1"
  ctrl_config: !cfg.type:ShutterController
    initial_state:        false                     # If T, signal is active low
