
# Mos configuration type definition
!cfg.include config/fcf/devmgr/definitions/device.yaml:

# Shutter configuration for the controller
!cfg.typedef MosController:
    timeout:     !cfg.type:uint32  2000

!cfg.typedef Mos(DeviceOpcua):
    type:        !cfg.type:string Mos
    mapfile:     !cfg.type:string "config/fcs/mapping/mos.yaml"
    ctrl_config: !cfg.type:MosController
