MetaExpoType:         "DET.EXPO.TYPE"
MetaExpoTime:         "DET.EXPO.TIME"
MetaExpoWinBinX:      "DET.EXPO.WIN.BINX"
MetaExpoWinBinY:      "DET.EXPO.WIN.BINY"
MetaExpoWinStartX:    "DET.EXPO.WIN.STARTX"
MetaExpoWinStartY:    "DET.EXPO.WIN.STARTY"
MetaSystem:           "DET.SYSTEM"
MetaCamName:          "DET.CAM.NAME"
MetaCamId:            "DET.CAM.ID"
MetaCamModel:         "DET.CAM.MODEL"
MetaCamChipModel:     "DET.CAM.CHIP.MODEL"
MetaCamType:          "DET.CAM.TYPE"
